import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <p className="bg-red-300">root layout</p>
        <Link href="/" className="bg-blue-300 mx-4">
          HOME
        </Link>
        <Link href="/dashboard" className="bg-blue-300">
          DASHBOARD
        </Link>
        {children}
      </body>
    </html>
  );
}
